name: Build

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Install Dependencies
        run: dkp-pacman -Syu --noconfirm 3ds-dev 3ds-curl 3ds-mbedtls 3ds-zlib 3ds-libopus 3ds-bannertool 3ds-makerom bannertool makerom || true

      - name: Build libsodium
          bash tools/setup_libsodium.sh

      - name: Build TriCord
        run: |
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TriCord-build
          path: |
            TriCord.3dsx
